buildImage = "ghcr.io/railwayapp/nixpacks:latest"

[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm", "openssl"]
nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee"
