import logo from '../images/logo.png'
import Image from 'next/image'
import moment from 'moment'
import { FaTimesCircle } from 'react-icons/fa'

const InvoiceTemplate = ({ stdPaymentInfo }) => {
  const student = stdPaymentInfo !== null && stdPaymentInfo

  if (student) {
    return (
      <div className='modal-body'>
        <div className='container'>
          <div className='img-box text-center'>
            <Image
              width='120'
              height='120'
              priority
              src={logo}
              alt='logo'
              className='img-fluid'
            />
            <br />
            {!student.isPaid && (
              <span className='badge rounded-pill bg-danger p-2 mt-3'>
                PAYMENT FEE UNPAID
              </span>
            )}
          </div>
          <div className='d-flex justify-content-between'>
            <span className='text-primary fw-bold fs-4'>INVOICE</span>
            <span className='text-primary'>Invoice No: {student.invoice}</span>
          </div>
          <div className='border border-1 border-primary rounded-3 p-3'>
            <div className='row'>
              <div className='col text-start'>
                STUDENT NAME: {student.student.fullName}
              </div>
              <div className='col text-center'>
                PAYMENT METHOD: {student.paymentMethod}
              </div>
              <div className='col text-end'>
                DATE:{' '}
                {student.isPaid ? (
                  moment(student.paymentDate).format('llll')
                ) : (
                  <FaTimesCircle className='text-danger mb-1' />
                )}
              </div>
            </div>

            <div className='row'>
              <div className='col text-start'>
                STUDENT ID: {student.student.rollNo}
              </div>
              <div className='col text-center'>
                COURSE: {student.course && student.course.name}
              </div>
              <div className='col text-end'>SHIFT: {student.shift}</div>
            </div>
          </div>

          <table className='table mt-3'>
            <thead>
              <tr className='bg-primary text-light'>
                <th scope='col'>#</th>
                <th scope='col'>COURSE</th>
                <th scope='col'>FEE</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope='row'>1</th>
                <td>{student.course && student.course.name}</td>
                <td>
                  {student.isPaid ? (
                    `$${student.amount.toFixed(2)}`
                  ) : (
                    <FaTimesCircle className='text-danger mb-1' />
                  )}
                </td>
              </tr>
              <tr className='bg-primary text-light'>
                <td colSpan='2 ' className='text-center'>
                  TOTAL
                </td>
                <td>
                  {student.isPaid ? (
                    `$${student.amount.toFixed(2)}`
                  ) : (
                    <FaTimesCircle className='text-danger mb-1' />
                  )}
                </td>
              </tr>
            </tbody>
          </table>
          <div className='row'>
            <div className='col-6'>E & O.E</div>
            <div className='col-6'>Accounts are due on demand</div>
            <div className='col-12 text-center my-3'>
              Generated by the system
            </div>
            <div className='col-6'>
              <span className='fw-bold'>Main Campus:</span> <br />
              <address>
                <span>Noorein St., Alanley, Beled-Hawa, Somalia</span> <br />
                <span>Tel: +252 (0) 699 484 972, +252 (0) 616 422 553</span>
                <br />
                <span>
                  Email:{' '}
                  <a href='mailto:info@samtec.so' target='blank'>
                    info@samtec.so
                  </a>
                </span>
              </address>
            </div>
            <div className='col-6'>
              <span className='fw-bold'>Laison Office:</span> <br />
              <address>
                <span>2nd Floor, Wing,B, Jamia Plazza, Kigali St.</span> <br />
                <span>P.O. Box 106239-00101 Nairobi, Kenya</span> <br />
                <span>Tel: +254 (0) 202 385 312</span>
              </address>
            </div>
            <div className='col-12 text-center my-3 bg-primary text-light p-3'>
              <a
                href='https://www.samtec.so'
                target='blank'
                className='text-light'
              >
                {' '}
                https://www.samtec.so
              </a>
            </div>
          </div>
        </div>
      </div>
    )
  } else return <span>Nothing</span>
}

export default InvoiceTemplate
