import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Card, CardContent, CardFooter, CardHeader } from '@/components/ui/card'
import Image from 'next/image'
import DateTime from '@/lib/dateTime'
import { FormatNumber } from './FormatNumber'

interface TransactionProp {
  id: string
  amount: number
  paymentStatus: 'UNPAID' | 'PAID'
  type: 'TUITION_PAYMENT' | 'ENROLLMENT_FEE'
  semester?: number
  shift?: 'MORNING' | 'AFTERNOON'
  createdAt: Date
  updatedAt: Date
  student?: {
    rollNo?: string
    name?: string
  }
  course?: {
    name?: string
  }
}

export const InvoiceCard = ({ data }: { data?: TransactionProp }) => {
  const isTuition = data?.type === 'TUITION_PAYMENT'

  return (
    <Card>
      <CardHeader>
        <div className='flex flex-col text-center'>
          <Image
            src='/logo.png'
            alt='logo'
            width={100}
            height={100}
            className='mx-auto'
          />
          <h2 className='text-2xl font-bold uppercase text-primary'>
            SAYID MOHAMED TECHNICAL EDUCATION COLLEGE <br />
            (SaMTEC)
          </h2>
          <span>
            Invoice No:{' '}
            {DateTime(data?.createdAt).format('YYYYMMDD') +
              data?.student?.rollNo}{' '}
            <br />
          </span>
          <span className='text-primary'>
            {DateTime(data?.createdAt).format('MMM YYYY')} <br />
          </span>
        </div>
        <hr className='mt-2' />
      </CardHeader>
      <CardContent>
        <div className='w-full p-4 space-y-2 border rounded'>
          <div className='grid grid-cols-3 gap-1'>
            <span>
              Student:
              <span className='font-bold'> {data?.student?.name}</span>
            </span>
            <span className='text-center'>
              Payment Method:
              <span className='font-bold'> on_cash</span>
            </span>
            <span className='text-end'>
              Date:
              <span className='font-bold'>
                {' '}
                {DateTime(data?.updatedAt).format('YYYY-MM-DD')}
              </span>
            </span>
          </div>

          <div className='grid grid-cols-3 gap-1'>
            <span>
              Roll No:
              <span className='font-bold'> {data?.student?.rollNo}</span>
            </span>
            <span className='text-center'>
              Course:
              <span className='ml-1 font-bold'>
                {isTuition ? (
                  <>
                    {data?.course?.name} ({data?.semester})
                  </>
                ) : (
                  <span className='text-red-500'>No Available</span>
                )}
              </span>
            </span>
            <span className='text-end'>
              Shift:
              <span className='ml-1 font-bold'>
                {isTuition ? (
                  data?.shift
                ) : (
                  <span className='text-red-500'>No Available</span>
                )}
              </span>
            </span>
          </div>
        </div>
        <Table className='my-5'>
          <TableHeader>
            <TableRow className='bg-primary hover:bg-primary'>
              <TableHead className='text-white'>
                {isTuition ? 'Course' : 'Type'}
              </TableHead>
              <TableHead className='text-white'>Fee</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>
                {isTuition ? data?.course?.name : 'Enrollment'}
              </TableCell>
              <TableCell>
                <FormatNumber value={data?.amount || 0} />
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <div className='grid grid-cols-2 gap-2 p-2'>
          <p>E & O.E</p>
          <p>Accounts are due on demand</p>
        </div>

        <div className='grid grid-cols-2 gap-2 p-2'>
          <p>
            <span className='font-bold'>Main Campus:</span> <br />
            Noorein St., Alanley, Beled-Hawa, Somalia Tel: +252 (0) 699 484 972,
            +252 (0) 616 422 553 <br />
            Email:{' '}
            <a href='mailto:info@samtec.so' className='underline'>
              info@samtec.so
            </a>
          </p>
          <p>
            <span className='font-bold'>Laison Office:</span> <br />
            2nd Floor, Wing,B, Jamia Plazza, Kigali St. P.O. Box 106239-00101
            Nairobi, Kenya
            <br />
            Tel:{' '}
            <a href='tel:+254202385312' className='underline'>
              +254 (0) 202 385 312
            </a>
          </p>
        </div>
      </CardContent>
      <hr className='mb-2' />
      <CardFooter>
        <div className='mx-auto my-2 text-center'>
          <span className='text-sm'>
            Generated by the system at:{' '}
            {DateTime(new Date()).format('YYYY-MM-DD hh:mm:ss')}
          </span>
        </div>
      </CardFooter>
    </Card>
  )
}
