import logo from '../logo.png'

const InvoicePrintScreen = (stdPaymentInfo) => {
  if (stdPaymentInfo) {
    return (
      <div className='modal-body'>
        {' '}
        {/* {JSON.stringify(stdPaymentInfo)}{' '} */}
        <div className='container'>
          <div className='img-box text-center'>
            <img src={logo} alt='logo' className='img-fluid' width='120' />
          </div>
          <div className='d-flex justify-content-between'>
            <span className='text-primary fw-bold fs-4'>INVOICE</span>
            <span className='text-primary'>Invoice No: 0751</span>
          </div>
          <div className='border border-1 border-primary rounded-3 p-3'>
            <div className='row'>
              <div className='col text-start'>
                STUDENT NAME: Abdi Ali Abdirahman
              </div>
              <div className='col text-end'>DATE: Tue 20th Oct, 2021</div>
            </div>

            <div className='row'>
              <div className='col text-start'>STUDENT ID: STD7</div>
              <div className='col text-center'>Course: Midwifery</div>
              <div className='col text-end'>Shift: Morning</div>
            </div>
          </div>

          <table class='table mt-3'>
            <thead>
              <tr className='bg-primary text-light'>
                <th scope='col'>#</th>
                <th scope='col'>COURSE</th>
                <th scope='col'>FEE</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope='row'>1</th>
                <td>Midwifery</td>
                <td>$12.00</td>
              </tr>
              <tr className='bg-primary text-light'>
                <td colspan='2 ' className='text-center'>
                  TOTAL
                </td>
                <td>$12.00</td>
              </tr>
            </tbody>
          </table>
          <div className='row'>
            <div className='col-6'>E & O.E</div>
            <div className='col-6'>Accounts are due on demand</div>
            <div className='col-12 text-center my-3'>
              Generated by the system
            </div>
            <div className='col-6'>
              <span className='fw-bold'>Main Campus:</span> <br />
              <address>
                <span>Noorein St., Alanley, Beled-Hawa, Somalia</span> <br />
                <span>
                  Tel: +252 (0) 699 484 972, +252 (0) 616 422 553
                </span>{' '}
                <br />
                <span>Email: info@samtec.so</span>
              </address>
            </div>
            <div className='col-6'>
              <span className='fw-bold'>Laison Office:</span> <br />
              <address>
                <span>2nd Floor, Wing,B, Jamia Plazza, Kigali St.</span> <br />
                <span>P.O. Box 106239-00101 Nairobi, Kenya</span> <br />
                <span>Tel: +254 (0) 202 385 312</span>
              </address>
            </div>
            <div className='col-12 text-center my-3 bg-primary text-light p-3'>
              https://www.samtec.so
            </div>
          </div>
        </div>
      </div>
    )
  } else return <span>Nothing</span>
}

export default InvoicePrintScreen
